# Generated by Django 5.0.6 on 2024-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('terminal', 'Terminal'), ('coffee_machine', 'Coffee Machine'), ('force_meter', 'Force Meter'), ('game_console', 'Game Console')], max_length=100),
        ),
    ]
