# Generated by Django 5.0.6 on 2024-05-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0004_alter_equipment_type'),
        ('workers', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='detected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_alerts', to='workers.profile'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='workers.profile'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_equipment', to='workers.profile'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipment', to='workers.profile'),
        ),
    ]
